### ISSUE TITLE
Section on Eclipse Plugins still named after OASP

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-guide#58]
### Expected behavior

As a reader od the devonfw guide, I want to read about the defonfw-ide, so that I can understand what it is

### Actual behavior

As can be seen on https://devonfw.com/website/pages/docs/master-ide.asciidoc_integrated-development-environment.html#eclipse-plugins.asciidoc , the section on eclipse plugins still refers to OASP: "5.15. OASP4J IDE Plugins:

Since an application’s code can greatly vary, and every program can be written in lots of ways without being semantically different, OASP4J IDE comes with pre-installed and pre-configured plugins that use some kind of a probabilistic approach, [...]"

This is totally confusing for everyone who does not know the history of the devonfw-ide.

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. go to https://devonfw.com/website/pages/docs/master-ide.asciidoc_integrated-development-environment.html#eclipse-plugins.asciidoc 

OR

take a look at eclipse-plugins.asciidoc

### Affected version: 2019-12-20 / No Version on devonfw-guide available (???)

* OS: Windows/Linux/Mac? all
* Browser: Chrome/Firefox/Safari? all

**Comment by Jan-PeterRichterCG** [comment]
There seems to have been a move/copy of some content to section 4.3 "The Devon IDE": When I go to https://devonfw.com/website/pages/docs/getting-started-the-devon-ide.asciidoc.html#getting-started-the-devon-ide.asciidoc_ide-plugins , I find some text that is very similar to the OASP-IDE related text. But this time, it reads ...: "
4.3. IDE Plugins:

Since an application’s code can greatly vary, and every program can be written in lots of ways without being semantically different, IDE comes with pre-installed and pre-configured plugins that use some kind of a probabilistic approach, usually based on pattern matching, to determine which pieces of code should be reviewed. [...]" 

I would prefer to find the detailed discussion of eclipse plugins unter section _5. Integrated Development Environment_ which is the main section on the IDE, not under section _4. The Devon IDE_ which is the the introductory section within the _Getting Started_ part of the guide.

**Comment by Jan-PeterRichterCG** [comment]
Hmmmmm.. the bug may have already been solved in some way: I have cloned the ide git repository in order to build my own ide distribution as recommended on https://devonfw.com/website/pages/docs/master-ide.asciidoc_integrated-development-environment.html#h45d9f31a22e3a03fa76cc84608ce6705.asciidoc ("ATTENTION..."). This home-brewn distribution contains a generated PDF-File devonfw-ide-doc.pdf and that PDF does not contain a subsection on eclipse plugins after the section on _Advanced Tooling_ .

It seems the online HTML-Version of the Guide is not quite up to date...

Anyhow, a comprehensive gude on the devon ide, as devon-ide-doc.pdf obviously is, should include the section on plugins (unless it is outdated anyway).

**Comment by maybeec** [comment]
should all be fixed. Thanks for the feedback.
