### ISSUE TITLE
Installation of CobiGen Eclipse Integration not usable for Non-Capgemini user

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-guide#59]
[Note: see also https://github.com/devonfw/ide/issues/330#issue-544502711 for an in-depth description of all the problems with Installation of CobiGen Eclipse Integration.]

As a non-Capgemini user, I want to install CobiGen Eclipse Integration so that I can use it.

When I follow the steps described in Section 54 _Eclipse Integration_ (see https://github.com/devonfw/devonfw-guide/raw/master/devonfw_guide.pdf ), I am stuck with...

Open CobiGen’s update site
Insert the update site of your interest into the filed Work with and press Add …
◦ Stable releases: http://de-mucevolve02/files/cobigen/updatesite/stable/
◦ Beta/RC releases: http://de-mucevolve02/files/cobigen/updatesite/experimental/

These URLs are not accessible from outside the Capgemini organization.

Is this intended (e.g. for reasons of intellectual property)? Then, please explicitly express this restriction. If not, please provide download-locations available from outside.

I know that the pre-configures ide will include the CobiGen integration (as soon as it is available). But also non-Capgemini users may want to install the CobiGen integration by themselves.

**Comment by maybeec** [comment]
@Jan-PeterRichterCG , @markusschuh , as of discussions with legal regarding public distribution of packaged solutions like CobiGen eclipse installation bundles, we needed to take them offline.
Now we are currently in the process to redistribute them by assuring correct licensing texts shipped with the bundles.

**Comment by maybeec** [comment]
fixed.
