### ISSUE TITLE
Section on Eclipse Plugins describes FindBugs, not SpotBugs

### ISSUE THREAD

**Issue by Jan-PeterRichterCG** [devonfw/devonfw-guide#61]
### Expected behavior

As a reader of the devonfw-guide, I want read up-to-date information on devonfw and devonfw-ide so that I can use it properly

### Actual behavior
Section 4.3.2 of the devonfw-guide (which is ide.wiki / eclipse-plugins.asciidoc) describes FindBugs, not SpotBugs, the actually installed plugin

### Steps to reproduce (bug) / Use Case of feature request (enhancement)

1. read section 4.3.2 of the devonfw-guide

### Comments/Hints:
https://marketplace.eclipse.org/content/findbugs-eclipse-plugin
https://marketplace.eclipse.org/content/spotbugs-eclipse-plugin

**Comment by maybeec** [comment]
fixed.
